imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        #handler_id: session.handler.pdo
        handler_id: snc_redis.session.handler
        # handler_id set to null will use default session handler from php.ini
        cookie_lifetime: 3153600
        gc_maxlifetime: 3153600

    fragments:       ~
    http_method_override: true
    esi: { enabled: true }

services:
    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            - { db_username: %database_user%, db_password: %database_password% }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@form.csrf_provider"
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [AppBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
    session:
        client: default

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
             datetime_functions:
                  date: DoctrineExtensions\Query\Mysql\Date     

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true
            sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    sender_address: "%mailer_sender%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    registration:
        form:
            type: app_user_registration
    resetting:
        email:
            from_email:
                address: "%mailer_sender%"
                sender_name: "Entrelectores"

hwi_oauth:
    connect:
        account_connector: fos_oauth_provider
        confirmation: false
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_app_id%"
            client_secret:       "%facebook_app_secret%"
            scope:               "email"
            options:
                display: popup

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.admin.block.search_result:
            contexts:   [admin]


sonata_admin:
    title: Entrelectores Admin
    templates:
       layout:              AdminBundle::new_standard_layout.html.twig
       user_block:          AdminBundle:Core:user_block.html.twig
    dashboard:
        groups:
            general:
                label: "General"
                items:
                    - admin.admin.book
                    - admin.admin.author
                    - admin.admin.genre
                    - admin.admin.review
                    - admin.admin.user
                    - admin.admin.book_list
            blog:
                label: "Blog"
                items:
                    - admin.admin.post
                    - admin.admin.post_category
            others:
                label: "Otros"
                items:
                    - admin.admin.poll
                    - admin.admin.interview
                    - admin.admin.banner
                    - admin.admin.page_banner

gregwar_image:
    cache_dir:  'img_cache'
    throw_exception: false
    fallback_image: '%kernel.root_dir%/../web/wp-content/no-cover.jpg'

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        
        
ivory_ck_editor:
    configs:
        default:
            toolbar:                [ [ "Source", "-", "Save","NewPage","Preview","Image","Maximize","ShowBlocks","-","-","Find","Replace","-","SelectAll","-", "Scayt" ], "/", [ "Bold","Italic","Underline","RemoveFormat","Cut","Copy","Paste","PasteText","-","Link","Unlink","Anchor","Table" ],"/", [ "Styles","Format","FontSize","Maximize" ]]
            uiColor:                "#fffffff"
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
               #instance: ckeditor


fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other choices are tinymce, simple, form or custom
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        showhidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

mapado_simstring:
    databases:
        book: 
            path: "%kernel.root_dir%/Resources/simstringdb/book.db"
            persistence:
                driver: orm # only ORM is supported for the moment
                model: \AppBundle\Entity\Book # required
                field: searchString # required
        author: 
            path: "%kernel.root_dir%/Resources/simstringdb/author.db"
            persistence:
                driver: orm # only ORM is supported for the moment
                model: \AppBundle\Entity\Author # required
                field: searchString # required
    reader:
        book:
            database: book
            measure: cosine # values are cosine/dice/jaccard/overlap/exact (default is: exact)
            threshold: 0.5 # float between 0 and 1
            min_results: 1
        author:
            database: author
            measure: cosine # values are cosine/dice/jaccard/overlap/exact (default is: exact)
            threshold: 0.5 # float between 0 and 1
            min_results: 1
    writer:
        book:
            database: book
        author:
            database: author
