security:                                 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        AppBundle\Entity\User:
            id: app.pass_encoder

    firewalls:
        main:
            entry_point: app.login_entry_point
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_referer:    false
                use_forward:    true
                default_target_path: /user_homepage
                always_use_default_target_path: true
            
            logout:       true
            anonymous:    true
            switch_user: { role: ROLE_ADMIN}
            oauth:
                resource_owners:
                    facebook:       "/oauth/login/check-facebook"

                login_path:        /oauth/login
                failure_path:      /oauth/login
                use_forward:       false
                default_target_path: /user_homepage
                use_referer: false
                oauth_user_provider:
                    service: fos_oauth_provider

    access_control:
        - { path: ^/oauth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/efconnect, role: ROLE_ADMIN }
        - { path: ^/elfinder, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
